#- name: Deploy application
#  hosts: app
#  tags: app-tag
#  become: true
- name: Configure App
  hosts: app
  become: true

  vars:
    db_host: 10.128.0.8

  tasks:

    - name: Add unit file for Puma
      copy:
        src: ./files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        mode: 0644
        owner: ubuntu
        group: ubuntu
      notify:
        - restart puma

    - name: enable puma
      systemd: name=puma enabled=yes
      notify:
        - restart puma

  #######################################
  handlers:

    - name: reload puma
      become: true
      systemd: name=puma state=restarted
