- name: Deploy App
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
    - name: install  git
      ansible.builtin.apt:
        update_cache: yes
        state: present
        name:
          - git

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
